@startuml

title __CONTROL's Class Diagram__\n

  package  {
    package control {
      class SearchController {
          - airports : ArrayList<Airport>
          + SearchController()
          + searchForFlight()
          + routeCalculation()
          + getAirports()
          - convertFlightTimeToDate()
          - convertStringToMinutes()
          + retrieveAirports()
          - retrieveFlights()
          - jsonObjectToFlight()
          - retrieveDiscountByFlightID()
          - jsonObjectToAirport()
      }
    }
  }
  

  package  {
    package control {
      class UIController {
          {static} + shared : UIController
          - routeOrigin : String
          - routeDestination : String
          + UIController()
          + logIn()
          + register()
          + searchForFlights()
          + applyDiscount()
          + logout()
          + checkForHigherAccess()
      }
    }
  }
  

  package  {
    package control {
      class UserControl {
          + UserControl()
          + getUser()
          + createUser()
          - validateUsername()
          - validatePassword()
      }
    }
  }
  

  package  {
    package control {
      class mainTest {
          {static} + main()
      }
    }
  }
  

  SearchController o-- getRequestHandler : dbHandler
  SearchController o-- Grapher : shortestPath
  UIController o-- User : currentUser
  UIController o-- UserControl : userCon
  UserControl o-- SimpleUserFactory : userFactory
  UserControl o-- getRequestHandler : dbPullHandler
  UserControl o-- insertRequestHandler : dbInsertHandler


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
